<?php /** Habr Pro - Register - flat */ $registrationDisabled=$registration_disabled??false; $errorMessage=$error??''; ?>
<?php if($registrationDisabled){ ?>
<div style="max-width:400px;margin:40px auto;padding:0 20px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif"><div style="border:1px solid #000;background:#fff;padding:20px;text-align:center"><div style="font-size:10px;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#8a8a8a;margin-bottom:8px">registration disabled</div><h2 style="font-size:16px;font-weight:800;margin:0 0 8px"><?= LANG_TEMPLATE_AUTH_REGISTER_DISABLED_TITLE ?></h2><p style="font-size:12px;color:#6c6c6c"><?= $errorMessage?html($errorMessage):LANG_TEMPLATE_AUTH_REGISTER_DISABLED_TEXT ?></p><a href="<?= BASE_URL ?>/login" style="display:inline-block;margin-top:12px;padding:6px 12px;background:#000;color:#fff;border:1px solid #000;font-size:11px;font-weight:700;text-transform:uppercase;text-decoration:none"><?= LANG_TEMPLATE_AUTH_LOGIN_BTN ?></a></div></div>
<?php }else{ ?>
<div style="max-width:480px;margin:40px auto;padding:0 20px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif">
  <div style="border:1px solid #000;background:#fff;padding:20px">
    <div style="margin-bottom:16px"><div style="font-size:10px;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#8a8a8a;margin-bottom:6px">auth / register</div><h1 style="font-size:20px;font-weight:800;margin:0;letter-spacing:-.02em"><?= LANG_TEMPLATE_AUTH_REGISTER_TITLE ?></h1><p style="font-size:12px;color:#6c6c6c;margin:6px 0 0"><?= LANG_TEMPLATE_AUTH_REGISTER_SUBTITLE ?></p></div>
    <div style="display:grid;grid-template-columns:repeat(2,1fr);gap:0;border:1px solid #e8e8e8;margin-bottom:16px">
      <div style="padding:8px;border-right:1px solid #e8e8e8;border-bottom:1px solid #e8e8e8;font-size:11px;color:#6c6c6c">— <?= LANG_TEMPLATE_AUTH_REGISTER_BENEFIT_COMMENT ?></div>
      <div style="padding:8px;border-bottom:1px solid #e8e8e8;font-size:11px;color:#6c6c6c">— <?= LANG_TEMPLATE_AUTH_REGISTER_BENEFIT_PROFILE ?></div>
      <div style="padding:8px;border-right:1px solid #e8e8e8;font-size:11px;color:#6c6c6c">— <?= LANG_TEMPLATE_AUTH_REGISTER_BENEFIT_DOWNLOADS ?></div>
      <div style="padding:8px;font-size:11px;color:#6c6c6c">— <?= LANG_TEMPLATE_AUTH_REGISTER_BENEFIT_ACHIEVEMENTS ?></div>
    </div>
    <?php if(isset($error)&&$error){ ?><div style="border:1px solid #000;border-left:3px solid #000;background:#f5f5f5;padding:8px 10px;font-size:11px;margin-bottom:12px"><strong><?= LANG_TEMPLATE_AUTH_ERROR ?></strong> <?= html($error) ?></div><?php } ?>
    <form method="post" action="<?= BASE_URL ?>/register" id="tg-register-form" style="display:flex;flex-direction:column;gap:10px">
      <input type="hidden" name="csrf_token" value="<?= $csrf_token ?>">
      <div><label for="username" style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;display:block;margin-bottom:4px"><?= LANG_TEMPLATE_AUTH_USERNAME_LABEL ?> *</label><input type="text" id="username" name="username" placeholder="<?= LANG_TEMPLATE_AUTH_USERNAME_PLACEHOLDER ?>" required value="<?= html($username??'') ?>" minlength="3" maxlength="30" pattern="[a-zA-Z0-9_]+" style="width:100%;padding:8px 10px;border:1px solid #e8e8e8;font-size:13px;border-radius:0"><div style="font-size:10px;color:#8a8a8a;margin-top:4px"><?= LANG_TEMPLATE_AUTH_USERNAME_HINT ?></div></div>
      <div><label for="display_name" style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;display:block;margin-bottom:4px"><?= LANG_TEMPLATE_AUTH_DISPLAY_NAME_LABEL ?></label><input type="text" id="display_name" name="display_name" placeholder="<?= LANG_TEMPLATE_AUTH_DISPLAY_NAME_PLACEHOLDER ?>" value="<?= html($display_name??'') ?>" style="width:100%;padding:8px 10px;border:1px solid #e8e8e8;font-size:13px;border-radius:0"></div>
      <div><label for="email" style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;display:block;margin-bottom:4px"><?= LANG_TEMPLATE_AUTH_EMAIL_LABEL ?> *</label><input type="email" id="email" name="email" placeholder="<?= LANG_TEMPLATE_AUTH_EMAIL_PLACEHOLDER ?>" required value="<?= html($email??'') ?>" style="width:100%;padding:8px 10px;border:1px solid #e8e8e8;font-size:13px;border-radius:0"></div>
      <div><label for="password" style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;display:block;margin-bottom:4px"><?= LANG_TEMPLATE_AUTH_PASSWORD_LABEL ?> *</label><input type="password" id="password" name="password" placeholder="<?= LANG_TEMPLATE_AUTH_PASSWORD_PLACEHOLDER ?>" required minlength="6" style="width:100%;padding:8px 10px;border:1px solid #e8e8e8;font-size:13px;border-radius:0"></div>
      <div><label for="password_confirm" style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;display:block;margin-bottom:4px"><?= LANG_TEMPLATE_AUTH_PASSWORD_CONFIRM_LABEL ?> *</label><input type="password" id="password_confirm" name="password_confirm" placeholder="<?= LANG_TEMPLATE_AUTH_PASSWORD_PLACEHOLDER ?>" required style="width:100%;padding:8px 10px;border:1px solid #e8e8e8;font-size:13px;border-radius:0"></div>
      <label style="display:flex;gap:6px;font-size:11px;line-height:1.4"><input type="checkbox" name="terms" id="terms" required style="accent-color:#000"> <span><?= LANG_TEMPLATE_AUTH_TERMS_AGREE ?> <a href="<?= BASE_URL ?>/terms" target="_blank" style="color:#000;font-weight:700"><?= LANG_TEMPLATE_AUTH_TERMS_LINK ?></a> <?= LANG_TEMPLATE_AUTH_TERMS_AND ?> <a href="<?= BASE_URL ?>/privacy" target="_blank" style="color:#000;font-weight:700"><?= LANG_TEMPLATE_AUTH_PRIVACY_LINK ?></a></span></label>
      <button type="submit" style="padding:8px 16px;background:#000;color:#fff;border:1px solid #000;font-weight:700;font-size:12px;text-transform:uppercase;letter-spacing:.04em;cursor:pointer;width:100%"><?= LANG_TEMPLATE_AUTH_REGISTER_BTN ?></button>
    </form>
    <div style="margin-top:16px;padding-top:12px;border-top:1px solid #e8e8e8;display:flex;gap:12px;font-size:11px"><a href="<?= BASE_URL ?>/login" style="color:#000;text-decoration:none;font-weight:700;text-transform:uppercase"><?= LANG_TEMPLATE_AUTH_HAVE_ACCOUNT ?></a><span style="color:#d4d4d4">/</span><a href="<?= BASE_URL ?>/forgot-password" style="color:#6c6c6c;text-decoration:none"><?= LANG_TEMPLATE_AUTH_FORGOT_PASSWORD_LINK ?></a></div>
  </div>
</div>
<?php } ?>
