<?php /** Habr Pro - Comment Edit - flat */
$postId=$comment['post_id']??0; $post=$postModel->getById($postId); $postTitle=$post?$post['title']:LANG_TEMPLATE_COMMENT_EDIT_UNKNOWN_POST; $postSlug=$post?$post['slug']:''; $isAdmin=$isAdmin??false; $canEdit=AuthHelper::canEditComment($comment['user_id']??null);
if(!$canEdit){ echo '<div style="max-width:800px;margin:20px auto;padding:20px;font-family:-apple-system,BlinkMacSystemFont,sans-serif"><div style="border:1px solid #000;border-left:3px solid #000;background:#f5f5f5;padding:10px;font-size:12px">'.LANG_TEMPLATE_COMMENT_EDIT_NO_PERMISSION.'</div></div>'; return; }
?>
<div style="max-width:800px;margin:0 auto;padding:20px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif">
  <div style="margin-bottom:16px;padding-bottom:12px;border-bottom:1px solid #000"><div style="font-size:10px;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#8a8a8a;margin-bottom:4px">comment / edit / #<?= $comment['id'] ?></div><h1 style="font-size:18px;font-weight:800;margin:0"><?= $isAdmin?LANG_TEMPLATE_COMMENT_EDIT_TITLE_ADMIN:LANG_TEMPLATE_COMMENT_EDIT_TITLE ?></h1><p style="font-size:12px;color:#6c6c6c;margin:4px 0 0"><?= html($postTitle) ?></p></div>
  <div style="border:1px solid #e8e8e8;background:#fff;padding:12px;margin-bottom:12px;display:flex;justify-content:space-between;align-items:center;gap:12px">
    <div><div style="font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#8a8a8a;font-weight:700"><?= LANG_TEMPLATE_COMMENT_EDIT_POST_LABEL ?></div><a href="<?= BASE_URL ?>/post/<?= $postSlug ?>" style="font-size:13px;font-weight:700;color:#000;text-decoration:none"><?= html($postTitle) ?></a></div>
    <a href="<?= BASE_URL ?>/post/<?= $postSlug ?>" style="padding:6px 10px;background:#fff;border:1px solid #e8e8e8;font-size:11px;font-weight:700;text-transform:uppercase;text-decoration:none;color:#000">← <?= LANG_TEMPLATE_COMMENT_EDIT_BACK_BTN ?></a>
  </div>
  <?php if(!$isAdmin&&$comment['status']==='pending'){ ?><div style="border:1px solid #000;background:#f5f5f5;padding:8px 10px;font-size:11px;margin-bottom:12px"><strong><?= LANG_TEMPLATE_COMMENT_EDIT_MODERATION_TITLE ?></strong> <?= !AuthHelper::can('comment_edit_no_moderations')?LANG_TEMPLATE_COMMENT_EDIT_MODERATION_TEXT:LANG_TEMPLATE_COMMENT_EDIT_NO_MODERATION_TEXT ?></div><?php } ?>
  <form action="<?= BASE_URL ?>/comment/edit/<?= $comment['id'] ?>" method="post" style="border:1px solid #000;background:#fff;padding:16px">
    <div style="margin-bottom:12px"><label for="content" style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;display:block;margin-bottom:4px"><?= LANG_TEMPLATE_COMMENT_EDIT_CONTENT_LABEL ?> *</label><textarea name="content" id="content" rows="6" placeholder="<?= LANG_TEMPLATE_COMMENT_EDIT_CONTENT_PLACEHOLDER ?>" required style="width:100%;padding:8px 10px;border:1px solid #e8e8e8;font-size:13px;resize:vertical;border-radius:0"><?= html($comment['content']??'') ?></textarea><div style="font-size:10px;color:#8a8a8a;margin-top:4px"><?= LANG_TEMPLATE_COMMENT_EDIT_MIN_LENGTH_HINT ?></div></div>
    <?php if($isAdmin){ ?>
    <div style="border:1px solid #e8e8e8;padding:12px;margin-bottom:12px;background:#f5f5f5">
      <div style="font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;margin-bottom:8px"><?= LANG_TEMPLATE_COMMENT_EDIT_ADMIN_SETTINGS ?></div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:10px">
        <div><label style="font-size:10px;font-weight:700;text-transform:uppercase;display:block;margin-bottom:4px"><?= LANG_TEMPLATE_COMMENT_EDIT_AUTHOR_NAME_LABEL ?></label><input type="text" name="author_name" value="<?= html($comment['author_name']??'') ?>" style="width:100%;padding:6px 8px;border:1px solid #e8e8e8;font-size:12px"></div>
        <div><label style="font-size:10px;font-weight:700;text-transform:uppercase;display:block;margin-bottom:4px"><?= LANG_TEMPLATE_COMMENT_EDIT_AUTHOR_EMAIL_LABEL ?></label><input type="email" name="author_email" value="<?= html($comment['author_email']??'') ?>" style="width:100%;padding:6px 8px;border:1px solid #e8e8e8;font-size:12px"></div>
      </div>
      <div><label style="font-size:10px;font-weight:700;text-transform:uppercase;display:block;margin-bottom:4px"><?= LANG_TEMPLATE_COMMENT_EDIT_STATUS_LABEL ?></label><select name="status" style="padding:6px 8px;border:1px solid #e8e8e8;font-size:12px;background:#fff"><option value="pending" <?= ($comment['status']??'pending')==='pending'?'selected':'' ?>><?= LANG_TEMPLATE_COMMENT_EDIT_STATUS_PENDING ?></option><option value="approved" <?= ($comment['status']??'pending')==='approved'?'selected':'' ?>><?= LANG_TEMPLATE_COMMENT_EDIT_STATUS_APPROVED ?></option><option value="spam" <?= ($comment['status']??'pending')==='spam'?'selected':'' ?>><?= LANG_TEMPLATE_COMMENT_EDIT_STATUS_SPAM ?></option></select></div>
    </div>
    <?php } ?>
    <div style="display:flex;justify-content:space-between;gap:8px;padding-top:12px;border-top:1px solid #e8e8e8">
      <a href="<?= BASE_URL ?>/post/<?= $postSlug ?>" style="padding:6px 12px;background:#fff;border:1px solid #e8e8e8;color:#000;font-size:11px;font-weight:700;text-transform:uppercase;text-decoration:none"><?= LANG_TEMPLATE_COMMENT_EDIT_CANCEL_BTN ?></a>
      <div style="display:flex;gap:8px">
        <?php if(AuthHelper::canDeleteComment($comment['user_id']??null)){ ?><button type="button" onclick="if(confirm('<?= LANG_TEMPLATE_COMMENT_EDIT_DELETE_CONFIRM ?>')) window.location.href='<?= BASE_URL ?>/comment/delete/<?= $comment['id'] ?>'" style="padding:6px 12px;background:#fff;border:1px solid #e8e8e8;color:#8a8a8a;font-size:11px;font-weight:700;text-transform:uppercase;cursor:pointer"><?= LANG_TEMPLATE_COMMENT_EDIT_DELETE_BTN ?></button><?php } ?>
        <button type="submit" style="padding:6px 12px;background:#000;color:#fff;border:1px solid #000;font-size:11px;font-weight:700;text-transform:uppercase;cursor:pointer"><?= LANG_TEMPLATE_COMMENT_EDIT_SAVE_BTN ?></button>
      </div>
    </div>
    <div style="margin-top:16px;padding-top:12px;border-top:1px solid #f0f0f0;display:grid;grid-template-columns:1fr 1fr;gap:16px;font-size:11px;color:#6c6c6c">
      <div><div style="font-size:10px;font-weight:700;text-transform:uppercase;color:#000;margin-bottom:6px"><?= LANG_TEMPLATE_COMMENT_EDIT_INFO_TITLE ?></div><div><?= LANG_TEMPLATE_COMMENT_EDIT_CREATED_AT ?> <?= date('d.m.Y H:i',strtotime($comment['created_at'])) ?></div><?php if(!empty($comment['updated_at'])&&$comment['updated_at']!=$comment['created_at']){ ?><div><?= LANG_TEMPLATE_COMMENT_EDIT_UPDATED_AT ?> <?= date('d.m.Y H:i',strtotime($comment['updated_at'])) ?></div><?php } ?><div><?= LANG_TEMPLATE_COMMENT_EDIT_AUTHOR_LABEL ?> <?= html($comment['author_name']??LANG_TEMPLATE_COMMENT_EDIT_UNKNOWN_AUTHOR) ?></div></div>
      <div><div style="font-size:10px;font-weight:700;text-transform:uppercase;color:#000;margin-bottom:6px"><?= LANG_TEMPLATE_COMMENT_EDIT_TIPS_TITLE ?></div><div>— <?= LANG_TEMPLATE_COMMENT_EDIT_TIP_1 ?></div><div>— <?= LANG_TEMPLATE_COMMENT_EDIT_TIP_2 ?></div><div>— <?= LANG_TEMPLATE_COMMENT_EDIT_TIP_3 ?></div></div>
    </div>
  </form>
</div>
